### ISSUE TITLE
Updates to this repository are not being published to Slack

### ISSUE THREAD

**Issue by climathosphere** [UofSSpaceTeam/robocluster-manger#8]
I have noticed that updates and issues from this repository were not being published on the _Github_ and _Github-Issues_ channels on Slack. I'm not sure if this is mandatory or not, but it would be nice to have the updates published on Slack.

**Comment by ottopasuuna** [comment]
Sorry I didn't see this for so long, I'll get this set up in the next few days.

**Comment by ottopasuuna** [comment]
Testing Slack webhook for robocluster-manager.
